const AppLanguages = [
  { Name: "Amharic", Code: "am", LocalName: "አማርኛ", Active: 0 },
  { Name: "Arabic", Code: "ar", LocalName: "العربية", Active: 0 },
  { Name: "Basque", Code: "eu", LocalName: "Euskara", Active: 0 },
  { Name: "Bengali", Code: "bn", LocalName: "বাংলা", Active: 0 },
  { Name: "Bulgarian", Code: "bg", LocalName: "български", Active: 0 },
  { Name: "Catalan", Code: "ca", LocalName: "Català", Active: 0 },
  { Name: "Cherokee", Code: "chr", LocalName: "ᏣᎳᎩ", Active: 0 },
  { Name: "Chinese (PRC)", Code: "zh-CN", LocalName: "简体中文", Active: 0 },
  { Name: "Chinese (Taiwan)", Code: "zh-TW", LocalName: "繁體中文", Active: 0 },
  { Name: "Croatian", Code: "hr", LocalName: "Hrvatski", Active: 0 },
  { Name: "Czech", Code: "cs", LocalName: "Čeština", Active: 0 },
  { Name: "Danish", Code: "da", LocalName: "Dansk", Active: 0 },
  { Name: "Dutch", Code: "nl", LocalName: "Nederlands", Active: 0 },
  { Name: "English (UK)", Code: "en-GB", LocalName: "English", Active: 0 },
  { Name: "English (US)", Code: "en", LocalName: "English", Active: 1 },
  { Name: "Estonian", Code: "et", LocalName: "Eesti", Active: 0 },
  { Name: "Filipino", Code: "fil", LocalName: "Filipino", Active: 0 },
  { Name: "Finnish", Code: "fi", LocalName: "Suomi", Active: 0 },
  { Name: "French", Code: "fr", LocalName: "Français", Active: 0 },
  { Name: "German", Code: "de", LocalName: "Deutsch", Active: 0 },
  { Name: "Greek", Code: "el", LocalName: "Ελληνικά", Active: 0 },
  { Name: "Gujarati", Code: "gu", LocalName: "ગુજરાતી", Active: 0 },
  { Name: "Hebrew", Code: "iw", LocalName: "עברית", Active: 0 },
  { Name: "Hindi", Code: "hi", LocalName: "हिन्दी", Active: 0 },
  { Name: "Hungarian", Code: "hu", LocalName: "Magyar", Active: 0 },
  { Name: "Icelandic", Code: "is", LocalName: "Íslenska", Active: 0 },
  { Name: "Indonesian", Code: "id", LocalName: "Bahasa Indonesia", Active: 0 },
  { Name: "Italian", Code: "it", LocalName: "Italiano", Active: 0 },
  { Name: "Japanese", Code: "ja", LocalName: "日本語", Active: 0 },
  { Name: "Kannada", Code: "kn", LocalName: "ಕನ್ನಡ", Active: 0 },
  { Name: "Korean", Code: "ko", LocalName: "한국어", Active: 0 },
  { Name: "Latvian", Code: "lv", LocalName: "Latviešu", Active: 0 },
  { Name: "Lithuanian", Code: "lt", LocalName: "Lietuvių", Active: 0 },
  { Name: "Malay", Code: "ms", LocalName: "Bahasa Melayu", Active: 0 },
  { Name: "Malayalam", Code: "ml", LocalName: "മലയാളം", Active: 0 },
  { Name: "Marathi", Code: "mr", LocalName: "मराठी", Active: 0 },
  { Name: "Norwegian", Code: "no", LocalName: "Norsk", Active: 0 },
  { Name: "Polish", Code: "pl", LocalName: "Polski", Active: 0 },
  { Name: "Portuguese (Brazil)", Code: "pt-BR", LocalName: "Português (Brasil)", Active: 0 },
  { Name: "Portuguese (Portugal)", Code: "pt-PT", LocalName: "Português (Portugal)", Active: 0 },
  { Name: "Romanian", Code: "ro", LocalName: "Română", Active: 0 },
  { Name: "Russian", Code: "ru", LocalName: "Русский", Active: 0 },
  { Name: "Serbian", Code: "sr", LocalName: "Српски", Active: 0 },
  { Name: "Slovak", Code: "sk", LocalName: "Slovenčina", Active: 0 },
  { Name: "Slovenian", Code: "sl", LocalName: "Slovenščina", Active: 0 },
  { Name: "Spanish", Code: "es", LocalName: "Español", Active: 0 },
  { Name: "Swahili", Code: "sw", LocalName: "Kiswahili", Active: 0 },
  { Name: "Swedish", Code: "sv", LocalName: "Svenska", Active: 0 },
  { Name: "Tamil", Code: "ta", LocalName: "தமிழ்", Active: 0 },
  { Name: "Telugu", Code: "te", LocalName: "తెలుగు", Active: 0 },
  { Name: "Turkish", Code: "tr", LocalName: "Türkçe", Active: 1 },
  { Name: "Ukrainian", Code: "uk", LocalName: "Українська", Active: 0 },
  { Name: "Urdu", Code: "ur", LocalName: "اردو", Active: 0 },
  { Name: "Vietnamese", Code: "vi", LocalName: "Tiếng Việt", Active: 0 },
  { Name: "Welsh", Code: "cy", LocalName: "Cymraeg", Active: 0 },
];

export default AppLanguages;
